### ISSUE TITLE
Question about AUX 

### ISSUE THREAD

**Issue by dialmak** [dzurikmiroslav/esp32-evse#17]
Hi,
The configuration https://github.com/dzurikmiroslav/esp32-evse/blob/master/cfg/esp32devkitc/board.cfg says
```
#AUX
AUX_IN_1=y
AUX_IN_1_NAME=IN1
AUX_IN_1_GPIO=4

AUX_IN_2=y
AUX_IN_2_NAME=IN2
AUX_IN_2_GPIO=21

....

AUX_OUT_2=y
AUX_OUT_2_NAME=OUT1
AUX_OUT_2_GPIO=5
```
Вut in the electrical circuit https://oshwlab.com/dzurik.miroslav/esp32-devkit-evse these contacts GPIO=4,5,21 are not used.
These are optional functions, I think, but I want to clarify what role they play and how to correctly connect external connections to the board. I want to repeat the electrical circuit, first single-phase, then three-phase .... The software was reproduced, and everything works. Thank you.

**Comment by dzurikmiroslav** [comment]
Hi,
Yes you have right, these GPIOs are not used in that circuit. I commit that by mistake, when I was developing AUX script API...

**Comment by dialmak** [comment]
Ок. In a three-phase circuit, they are (I think) necessary. But what exactly and how is connected through these contacts. Can I get a schematic or wiring?

**Comment by dzurikmiroslav** [comment]
No, AUX are for additional input/output functionality (for example: enable charging in low tariff, limit charging current by button, show external status light when charging, etc...) controller in script driver (Berry lang).
ESP32-DevKitC board has single-phase energy meter (current transformer + voltage sensing), can you use in three-phase wallbox, but will not have real power & energy consumption. You can set energy meter type to "Dummy three phase", power & consumption will be calculated from provided AC voltage and actual Charging current.
![](https://raw.githubusercontent.com/wiki/dzurikmiroslav/esp32-evse/images/web-settings-emeter.png)
I was thinking that in the future I will add support for an external energy meter with RS485 modbus interface...

**Comment by dzurikmiroslav** [comment]
Any which has ratio 2000/1
In esp32-devkit-evse I was using SCT-013-000 (has jack connector)
In esp32s2-evse-d-a I was using DL-CT08CL5 0-120A (no connector)

**Comment by dialmak** [comment]
Thanks. 

The last question remains on the electrical circuit.
I want to add an electronic residual current device to the single-phase version. What circuit and sensor do you recommend? Is it possible to use the residual current device circuit from the three-phase version?

**Comment by dzurikmiroslav** [comment]
esp32s2-evse-d-a has RCM input for RCM14 https://webshop.westernautomation.com/ev-industry/rcm14-03-6ma-dc-15-30ma-ac-9013

esp32-devkit-evse has no RCM input, only option is use standard electrical residual current breaker (type B or other for EV) for example:
https://www.se.com/ww/en/product/A9Z51440/residual-current-circuit-breaker-rccb-acti9-iid-4p-40a-bev-electric-vehicle-type-30ma-double-terminal/

Other way is design custom board, for example based on esp32-devkit-evse and extend with RCM circuit form esp32s2-evse-d-a and write config for it.
