### ISSUE TITLE
ADC Reading

### ISSUE THREAD

**Issue by brunohorta82** [dzurikmiroslav/esp32-evse#32]
Hello, I having problems when I use the ENERGY_METER_L1_CUR_ADC_CHANNEL=4 and PILOT_ADC_CHANNEL=1.
When I get consumption the Pilot return Error.. It's strange how different IO's can interfere with each other.
I'm using ESP32. Any Ideas?

**Comment by dzurikmiroslav** [comment]
Hello, I need to see the complete `board.cfg`, this doesn't tell me much...
