### ISSUE TITLE
Flashing problem... 

### ISSUE THREAD

**Issue by dariusz737** [dzurikmiroslav/esp32-evse#51]
Hello. Great project. But I have a problem to flash DevKIt from esp32s2-evse.bin. Everything seems to be ok, no error on flashing. But after I have such error in logs. Does it matter that my board is different from one on GitHub? 
![Obrazek](https://github.com/dzurikmiroslav/esp32-evse/assets/81053092/94c3bc18-d49f-41e9-b6bb-30a144a904a6)
![att UQuX4cS8CXDEQ038XJZ_9qzgrmriPe74SgEMuN86spc (1)](https://github.com/dzurikmiroslav/esp32-evse/assets/81053092/5a5141ca-5e13-4f25-8754-ec095feb7237)

**Comment by dariusz737** [comment]
Hello 

Is it possible to flash esp32-evse.bin with this tool - https://esp.huhn.me/  

Best regrads
Dariusz Kulik 



 <https://github.com/dzurikmiroslav/esp32-evse/releases/download/v0.7.0/esp32-evse.bin>Wiadomość napisana przez Miroslav Dzúrik ***@***.***> w dniu 25.04.2024, o godz. 21:45:

**Comment by dariusz737** [comment]
Hello 

Finały with help of my friend I have managed to flash ESP32s2 and even connect to Home Assistant. 
We are successful to read data, but failed to sent two basic commands, ON-OFF charging and limit charging current. 
Can you please help with this? 

Best regards
Dariusz Kulik

**Comment by dzurikmiroslav** [comment]
Congrats to flash :-)
How do you read data from Home Assistant? HTTP API or Modbus RTU/TCP ?

**Comment by dariusz737** [comment]
MQTTWiadomość napisana przez Miroslav Dzúrik ***@***.***> w dniu 06.07.2024, o godz. 08:46:﻿
Congrats to flash :-)
How do you read data from Home Assistant? HTTP API or Modbus RTU/TCP ?

**Comment by Lagerkugel** [comment]
Hello Miroslav,

I am a Mac user and I am desperate about the Espressif IDE.

Would it be possible for you to write a short script for the initial compilation of the ESP32 code?

Or better:

Would it be possible for you to set up an esp32-evse.factory.bin to start it, which I could write to the ESP32 using any web installer and would immediately receive the required partitions and a generic configuration file. (See Tasmota)

I believe that many more users would realize the project if this point were checked off.
For me, the project would have died without your help.

cu Matthias

**Comment by dzurikmiroslav** [comment]
Hi,
I am know esphome web installer and its good feature. Better write one HTML/js protect then shell script for every platform...
I will try find free space to implement it.

**Comment by dzurikmiroslav** [comment]
There is ESP Web Tools installer like (Tasmota/esphome) https://dzurikmiroslav.github.io/esp32-evse/web-installer
In future I maybe implement Improv serial standard for setting WiFi connection...
