### ISSUE TITLE
PILOT_DOWN_TRESHOLD How get the best value?

### ISSUE THREAD

**Issue by brunohorta82** [dzurikmiroslav/esp32-evse#7]
Hello, you can explain the way how I can get PILOT_DOWN_TRESHOLD_X from a new board?
Thanks

**Comment by dzurikmiroslav** [comment]
Hi, I wrote article in doc/BOARD_CONFIG.md about that https://github.com/dzurikmiroslav/esp32-evse/blob/master/doc/BOARD_CONFIG.md#pilot_down_treshold_x-calculation

**Comment by dzurikmiroslav** [comment]
The previous article was incorrect, the EV resistance was not accounted for in the formula I used...
In the wiki, I described the procedure based on the simulation of the EV side:
https://github.com/dzurikmiroslav/esp32-evse/wiki/CP-calibration
